<!DOCTYPE html>
<html>
  <head>
    <title>web assembly string</title>
  </head>
  <body>
    <p>Check the console for a 42, followed by a 13, followed by an <em>Uncaught RuntimeError: index out of bounds</em> error. That's supposed to be there. The first two function calls succeeded, and there are no more than two functions defined in the module, so calling for the third function causes this error. 
    <a href="/">Back to index</a>
    <script type="module">
      /*
    function setupTable(){
      const tbl = new WebAssembly.Table({initial: 2, element: "anyfunc"})

      const f1 = () => console.log("Hello ",)
      const f2 = () => console.log("Worlds")

      tbl.set(0, f1)
      tbl.set(1, f2)

      return table
    }
    */

    WebAssembly.instantiateStreaming(
      fetch('table.wasm'),
    ).then((obj) => {
      console.log(obj.instance.exports.callByIndex(0))
      console.log(obj.instance.exports.callByIndex(1))
      try{
        console.log(obj.instance.exports.callByIndex(2))
      }catch(RuntimeError){
        console.error("Anticipated RuntimeError caught.")
      }
    })
    </script>
  </body>
</html>
